title: Julius's BJC Website
description: Introduction, Funny Image, Dog Chooser
theme: just-the-docs

url: https://juliuszhou124.github.io/website/
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
